apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: secretshare
  name: secretshare
spec:
  replicas: 2
  selector:
    app: secretshare
    deploymentconfig: secretshare
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: secretshare
        deploymentconfig: secretshare
    spec:
      containers:
      - env:
        - name: SECRETSHARE_BUCKET
          value: "BUCKET NAME GOES HERE"
        - name: SECRETSHARE_BUCKET_REGION
          value: "BUCKET REGION GOES HERE"
        - name: SECRETSHARE_SECRET_KEY
          value: "MAKE SOMETHING UP"
        - name: SECRETSHARE_AWS_KEY_ID
          value: "AWS KEY ID GOES HERE"
        - name: SECRETSHARE_AWS_SECRET_KEY
          value: "AWS SECRET KEY GOES HERE"
        image: "INITIAL istag GOES HERE"
        imagePullPolicy: Always
        name: secretshare
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 32Mi
          requests:
            cpu: 10m
            memory: 16Mi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - secretshare
      from:
        kind: ImageStreamTag
        name: secretshare:latest
    type: ImageChange
status: {}
