apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: secretshare
  name: secretshare
spec:
  ports:
  - name: 5000-tcp
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: secretshare
    deploymentconfig: secretshare
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
